##SnakeGame
SCREEN_HEIGHT = 500
SCREEN_WIDTH = 500
BOLD = "\033[1m"
RESET = "\033[0m"
GAMEOVER_POS = (0,SCREEN_HEIGHT*3/8)
SCORE_POS = (0,SCREEN_HEIGHT*0.4)
##Snake
STARTING_COORDINATE = (0,0)
SQUARE_SIZE:int = 20
START_SNAKE_SIZE = 3 
START_SNAKE_SPEED = 20
HIGH_SCORE_FILE = "highscore.txt"