BAR_SIZE = 20
STRETCHED_WIDTH=5
STRETCHED_LEN=0.5
REL_POSITION = 0.9
MOVE_SPEED = 20

WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500

REFRESH_RATE = 1000
DELTA = REFRESH_RATE / 100
# ball constrains
BALL_SIZE = 20
BALL_SIZE_FACTOR = 0.5
BALL_COLOR = "green"
BALL_X_VELOCITY = 3

# collision constraints
COLL_XMIN = - WINDOW_WIDTH * REL_POSITION // 2 + BAR_SIZE * STRETCHED_LEN + BALL_SIZE * BALL_SIZE_FACTOR // 2
COLL_XMAX =   WINDOW_WIDTH * REL_POSITION // 2 - BAR_SIZE * STRETCHED_LEN - BALL_SIZE * BALL_SIZE_FACTOR // 2
MISS_XMIN = - WINDOW_WIDTH * REL_POSITION // 2 + BALL_SIZE * BALL_SIZE_FACTOR // 2
MISS_XMAX =   WINDOW_WIDTH * REL_POSITION // 2 - BALL_SIZE * BALL_SIZE_FACTOR // 2
BALL_MAX_Y_VEL = 5

# physics
FRICTION = 1
ACCN = 4
BAR_MAX_VEL = 8

# score positions
SCORE_LEFT_X  = - WINDOW_WIDTH // 10
SCORE_RIGHT_X =   WINDOW_WIDTH // 10
SCORE_Y = WINDOW_HEIGHT * 2 // 5

STROKE_LENGTH = 20
PEN_WIDTH = 8