PICNAME = "blank_states_img.gif"
WINDOW_WIDTH = 725
WINDOW_HEIGHT = 491

#Timer
START_MINUTES = 0
START_SECONDS = 2
TIMER_POS_X = 250
TIMER_POS_Y = 200
TIMER_SIZE = 25
TIMER_BORDER_WIDTH = 100
TIMER_BORDER_HEIGHT = 35

#File
FILENAME = "50_states.csv"